hashicorp/terraform-provider-googleworkspace

.github/workflows/test.yml, GNUmakefile
=> update timeout again

internal/provider/provider_config.go
This will log http requests/responses and help with https://github.com/hashicorp/terraform-provider-googleworkspace/issues/88
=> add loggingTransport

docs/upgrade_guide.md, templates/upgrade_guide.md
Fixes https://github.com/hashicorp/terraform-provider-googleworkspace/issues/94
Add documentation on upgrading from the GSuite provider to the Google Workspace provider.
=> add upgrade documentation

docs/upgrade_guide.md, templates/upgrade_guide.md
Fixes https://github.com/hashicorp/terraform-provider-googleworkspace/issues/102
=> update upgrade guide with who_can_approve_members deprecation note

internal/provider/resource_schema.go
fixes https://github.com/hashicorp/terraform-provider-googleworkspace/issues/88
need to check if indexed is nil
=> fix indexed is nil error

internal/provider/resource_group_settings.go
Previously, in `< v0.3.0` of the provider, we forgot to check for a final error in the retry loop, users likely experienced a silent failure. As it turns out though, >= v0.3.0 when the timeout is surfaced, the timeout error itself was likely a false positive. We performed a reflect.DeepEqual on the 2 groupSettings objects, the problem is there is a hard to spot, embedded type `googleapi.ServerResponse`, which contains a timestamp. The resource would only ever pass if the settings were in fact consistent AND the 2 requests were performed in the same second (not so unlikely, but very prone to failure depending on system performance, network performance, and of course timing luck).
The `ServerResponse` proves useful as it has an Etag header which we can plug into our eventual consistency …
=> Fix group_settings consistency check

internal/provider/resource_user.go, internal/provider/resource_user_test.go
If a user specified multiple `custom_schemas` blocks, the data read back from the API often returned them out of order causing a diff with terraform. This is all made more complex in that we need to ensure the nested `schema_values` also don't have order diffs, an edgecase had to be added that ensured encoded lists `"[1, 2, 3]"` which google store as unordered "multi-values" also don't produce a diff if they are returned `"[2, 1, 3]"` (out of order).
Closes #121
=> Fix r/user custom_schemas permadiff

internal/provider/utils.go
Fixes https://github.com/hashicorp/terraform-provider-googleworkspace/issues/131
=> Fix: delete fields that are set to empty strings

docs/resources/user.md, internal/provider/resource_user.go, internal/provider/resource_user_test.go
fixed other things i noticed too (copy/paste issues)
=> all the  fields should be required on user

internal/provider/resource_group_member.go
Fixes https://github.com/hashicorp/terraform-provider-googleworkspace/issues/151
=> make email ForceNew on group_member

internal/provider/resource_user.go
Fixes https://github.com/hashicorp/terraform-provider-googleworkspace/issues/150
Workspace will return a list of email addresses (either defined user aliases or ones that are computed, such as the primary email, an associated test email and emails from other managed domains). In the case of computed emails, they seem to not have a type (this is an assumption based on what we've seen). So instead of hardcoding just the primary email and the associated test email, we'll ignore any emails that don't have a `type` set. This is possible because `type` is required in our configuration file.
=> suppress diff on any email addresses without a type, as those are computed

internal/provider/provider.go, internal/provider/provider_config.go, internal/provider/provider_config_test.go
fixes https://github.com/hashicorp/terraform-provider-googleworkspace/issues/140
=> add ability to use user credentials to authenticate

internal/provider/provider.go, internal/provider/provider_config.go, internal/provider/retry_predicates.go, internal/provider/retry_predicates_test.go, internal/provider/retry_transport.go, internal/provider/retry_transport_test.go, internal/provider/retry_utils.go, internal/provider/retry_utils_test.go
Fixes https://github.com/hashicorp/terraform-provider-googleworkspace/issues/159
Added retry transport which should fix rate-limiting issues
=> add retry transport

.github/infra/gcp.tf
needed to impersonate the user still
=> update permissions on access_token test service account

README.md
@megan07  - Can you please review this change to read me to include the google form.
=> Added a link to gather general feedback

internal/provider/resource_group_members.go
Add pagination to group_members read function.
Fixes https://github.com/hashicorp/terraform-provider-googleworkspace/issues/205
=> add pagination for group_members

internal/provider/resource_user.go
Looks like the underlying API changed beneath us. Making the fixes to what I noticed so far.
=> fix some issues after the user api seemed to be updated

docs/data-sources/user.md, docs/resources/user.md, internal/provider/resource_user.go
Fixes https://github.com/hashicorp/terraform-provider-googleworkspace/issues/233
Add `langauges.preference`
=> add langauges preference

CHANGELOG.md
=> add changelog for 0.6.0

internal/provider/resource_user.go, internal/provider/resource_user_test.go
Fixes https://github.com/hashicorp/terraform-provider-googleworkspace/issues/260
=> add force new fields to string fields as well

internal/provider/data_source_users.go, internal/provider/data_source_users_test.go
Fixes https://github.com/hashicorp/terraform-provider-googleworkspace/issues/270
=> add full projection for users list

.github/workflows/test.yml
Fixes https://github.com/hashicorp/terraform-provider-googleworkspace/issues/316
Might fix it, if not it addresses the warning in the output
=> Bump Go to 1.18 for Build step of acc-test action

internal/provider/resource_org_unit.go
fixes https://github.com/hashicorp/terraform-provider-googleworkspace/issues/310
=> fix eventual consistency with org unit
